#!/bin/bash
# Serve the static site locally and point the browser at your local API.
#
# Usage:
#   ./serve.sh                    # site :8002, API :8001
#   ./serve.sh 8000               # site :8000, API :8001
#   ./serve.sh 8000 9000          # site :8000, API :9000
#
# Env overrides:
#   JUNIOR_SITE_PORT=8002 JUNIOR_API_PORT=8001 ./serve.sh

set -e

SITE_PORT="${JUNIOR_SITE_PORT:-${1:-8002}}"
API_PORT="${JUNIOR_API_PORT:-${2:-8001}}"
API_HOST="${JUNIOR_API_HOST:-localhost}"
CONFIG_FILE="js/api-config.local.js"

if [[ "$SITE_PORT" =~ ^-h|--help|help$ ]] || [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
  echo "Usage: ./serve.sh [site-port] [api-port]"
  echo ""
  echo "  site-port   Port for this static site (default: 8002)"
  echo "  api-port    Port for your backend API   (default: 8001)"
  echo ""
  echo "Examples:"
  echo "  ./serve.sh              # http://localhost:8002 → API http://localhost:8001"
  echo "  ./serve.sh 8000         # http://localhost:8000 → API http://localhost:8001"
  echo "  ./serve.sh 8000 9000    # http://localhost:8000 → API http://localhost:9000"
  echo ""
  echo "Env: JUNIOR_SITE_PORT, JUNIOR_API_PORT, JUNIOR_API_HOST"
  exit 0
fi

if ! [[ "$SITE_PORT" =~ ^[0-9]+$ ]] || ! [[ "$API_PORT" =~ ^[0-9]+$ ]]; then
  echo "❌ Ports must be numbers. Got site=$SITE_PORT api=$API_PORT"
  echo "   Run: ./serve.sh --help"
  exit 1
fi

API_BASE="http://${API_HOST}:${API_PORT}"

mkdir -p "$(dirname "$CONFIG_FILE")"
cat > "$CONFIG_FILE" <<EOF
// Generated by ./serve.sh — do not commit (gitignored)
window.__JUNIOR_API_CONFIG__ = {
  localApiBaseUrl: '${API_BASE}'
};
EOF

echo "🚀 Local dev"
echo "   Site:  http://localhost:${SITE_PORT}"
echo "   API:   ${API_BASE}"
echo "   Wrote: ${CONFIG_FILE}"
echo ""
echo "   Try it: http://localhost:${SITE_PORT}/try-it.html"
echo ""
echo "Press Ctrl+C to stop"
echo ""

cleanup() {
  rm -f "$CONFIG_FILE"
}
trap cleanup EXIT INT TERM

if command -v python3 &> /dev/null; then
  python3 -m http.server "$SITE_PORT"
elif command -v python &> /dev/null; then
  python -m SimpleHTTPServer "$SITE_PORT"
elif command -v npx &> /dev/null; then
  npx serve -p "$SITE_PORT"
else
  echo "❌ No suitable server found. Install Python 3 or Node.js."
  exit 1
fi
